# Generated by Django 5.0.6 on 2024-06-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_type', models.IntegerField(choices=[(1, 'Stipendiya e’lonlari'), (2, 'Oliy ta’limdan keyingi ta’lim qabuli'), (3, 'Malakaviy imtihon'), (4, 'Himoya e’lonlari'), (5, 'Doktorantlarni ilmiy seminar e’lonlari'), (6, 'Konferensiya e’lonlari')])),
                ('title', models.CharField(max_length=1023)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='news/')),
                ('views', models.IntegerField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-added_date'],
            },
        ),
    ]
