# Generated by Django 5.0.6 on 2024-06-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_min_desc_alter_news_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='min_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
