# Generated by Django 5.0.6 on 2024-06-15 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-added_date']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-added_date']},
        ),
    ]
