# Generated by Django 5.0.6 on 2024-06-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_photo_options_alter_video_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='views',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=1),
        ),
    ]
